--- 
- hosts: localhost
  vars:
    userdata: "{{ lookup('file', 'files/user_data.txt') }}"
    DEMO_ACCESS_KEY : "{{ lookup('env','DEMO_ACCESS_KEY') }}"
    DEMO_SECRET_KEY: "{{ lookup('env','DEMO_SECRET_KEY') }}"

  tasks:

    - debug: var="{{ userdata }}"
    
    - name: Create node
      local_action:
            module: ec2
            aws_access_key: "{{ DEMO_ACCESS_KEY }}"
            aws_secret_key: "{{ DEMO_SECRET_KEY }}"
            key_name: ansible_demo
            group_id: sg-df39fbb2
            instance_type: c3.large
            image: ami-3615525e
            wait: yes
            wait_timeout: 400
            user_data: "{{ userdata }}"
            zone: us-east-1d
            region: us-east-1
      register: ec2
      tags:
        - build
    
    - local_action: ec2_tag resource={{ ec2.instance_ids[0] }} aws_access_key="{{ DEMO_ACCESS_KEY }}" aws_secret_key="{{ DEMO_SECRET_KEY }}" region=us-east-1
      args:
        tags:
          Name:  coreos001

    - name: Add host to group
      add_host: hostname={{ item.public_ip }} groupname=coreosnodes
      with_items: ec2.instances
      tags:
        - build

    - name: Add to inventory file
      local_action: lineinfile dest=/Users/Madhurranjan/Projects/personal/ansible_demo/inventory insertafter='[coreosnodes]' line={{ item.public_ip }}
      with_items: ec2.instances
      tags:
        - build


- hosts: coreosnodes
  gather_facts: false
  user: coreos
  roles:
    - role: defunctzombie.coreos-bootstrap
  tags: bootstrap

- hosts: coreosnodes
  gather_facts: false
  user: coreos
  sudo: true
  vars:
    web_version: latest
    image: madhurranjan/mamu_test
  tasks:
    #- name: Start docker container
    #  docker: image=fcat/rails-getting-started ports=3000
    #  tags: docker
    - name: Setup systemd service file
      template: src=templates/systemd_service.j2 dest=/etc/systemd/system/web.service owner=root mode=0644
      tags:
        - setup

    - name: Reload Daemon
      shell: /usr/bin/systemctl daemon-reload
      tags:
        - setup

    - name: Update environment variable file
      template: src=templates/env.j2 dest=/etc/systemd/env.conf owner=root mode=0644
      tags:
        - setup

    - name: Download docker image
      shell: /usr/bin/docker pull {{ image }}:{{ web_version }}
      tags:
        - setup

    - name: Enable systemd service files
      shell: /usr/bin/systemctl enable /etc/systemd/system/web.service
      ignore_errors: yes
      tags:
        - setup

    - name: Start systemd services
      shell: /usr/bin/systemctl start web.service
      tags:
        - setup
